USE [master]
GO

/****** Object:  Database [CAMPUS_PARTY]    Script Date: 26/05/2020 1:32:24 p. m. ******/
CREATE DATABASE [CAMPUS_PARTY]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'CAMPUS_PARTY', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CAMPUS_PARTY.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'CAMPUS_PARTY_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CAMPUS_PARTY_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CAMPUS_PARTY] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CAMPUS_PARTY].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CAMPUS_PARTY] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET ANSI_NULLS OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET ANSI_PADDING OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET ARITHABORT OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [CAMPUS_PARTY] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [CAMPUS_PARTY] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET  DISABLE_BROKER
GO

ALTER DATABASE [CAMPUS_PARTY] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [CAMPUS_PARTY] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET RECOVERY SIMPLE
GO

ALTER DATABASE [CAMPUS_PARTY] SET  MULTI_USER
GO

ALTER DATABASE [CAMPUS_PARTY] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [CAMPUS_PARTY] SET DB_CHAINING OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [CAMPUS_PARTY] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [CAMPUS_PARTY] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [CAMPUS_PARTY] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CAMPUS_PARTY] SET  READ_WRITE
GO


